### ISSUE TITLE
Express is not running.

### ISSUE THREAD

**Issue by ItzSudhan** [DiscordBotList/dblapi.js#23]
Express is not running while i add dbl webhook to my code

**Comment by tonkku107** [comment]
Please include more information like the code you have written and any errors

**Comment by ItzSudhan** [comment]
```js
const DBL = require('dblapi.js');
const dbl = new DBL(process.env.TOP_GG, { webhookPort: process.env.PORT, webhookAuth: 'Tqbb72c7beyu2qQDUwue' });

dbl.webhook.on('posted', () => {
console.log("posted");
})

const express = require('express')
const app = express()
app.get("/", (req, res) => {
res.send("Hi!")
})
```

When i gone to`` /`` its not working

**Comment by ItzSudhan** [comment]
@tonkku107 Sent

**Comment by tonkku107** [comment]
The code snippet is missing a listen call...    

Please also check the example for linking to an existing express server from the documentation.

If you need help setting things up, please ask in the #api channel in the discord server instead of creating an issue.
