### ISSUE TITLE
webhook issues

### ISSUE THREAD

**Issue by sambeano7** [DiscordBotList/dblapi.js#25]
getting this error
> dbl.webhook.on('ready', hook => {
>           ^
> TypeError: Cannot read property 'on' of undefined

with this code
> const DBL = require('dblapi.js');
> const dbl = new DBL(process.env.DBL_TOKEN, { webhook: 3000, webhookAuth: `notgivingmypassword` }, client);
> 
> dbl.webhook.on('ready', hook => {
>    console.log(`Webhook running at http://${hook.hostname}:${hookport}${hook.path}`)
> });

**Comment by tonkku107** [comment]
> webhook: 3000

Change to
> webhookPort: 3000

**Comment by tonkku107** [comment]
Please use the #api channel in the [discord server](https://discord.gg/dbl) for help with using the library in the future
