### ISSUE TITLE
When using `dblapi.js` in a TypeScript project, the typing mess things up.

### ISSUE THREAD

**Issue by succubus86** [DiscordBotList/dblapi.js#30]
When using `dblapi.js` in a TypeScript project, the typing mess things up.
With the following code, I get these errors `Property 'hostname' does not exist on type 'string'`, `Property 'port' does not exist on type 'string'` and `Property 'path' does not exist on type 'string'`.
```ts
dbl.webhook.on("ready", (hook) => {
  console.log(
    `Webhook running at https://${hook.hostname}:${hook.port}${hook.path}`
  );
});
```
This is because the typing file says that the callback function's signature should be like this:
```ts
(hostname: string, port: number, path: string) => void
```
which is not correct. The correct signature is something like this:
```ts
({hostname: string, port: number, path: string}) => void
```
Same thing for the `vote` event. I fixed the typing file so now it doesn't report any error in TypeScript projects.

_Originally posted by @zihadmahiuddin in https://github.com/top-gg/dblapi.js/pull/26#issuecomment-653417029_

**Comment by jpbberry** [comment]
This issue is out of date due to the new rewrite.
