### ISSUE TITLE
[Sharding] How to pass shard client into webhook server (express)

### ISSUE THREAD

**Issue by HellCatVN** [DiscordBotList/dblapi.js#38]
is there any specific how to using this library with multiple sharding bot

**Comment by jpbberry** [comment]
There's no way to pass client to anything in this library. However I'm a little confused about what you mean passing your client to the webhook, what purpose would this serve?

**Comment by HellCatVN** [comment]
I want to send message to user how just vote my bot in case I am using multiple sharding

**Comment by jpbberry** [comment]
You can just DM the user via the Discord API with the webhook hosted on the master process or another process. The webhook serves as a receiver for top.gg webhooks, it wouldn't assume the responsibility of DMing users or anything like that. You can easily do it yourself though!

**Comment by HellCatVN** [comment]
Currently I am using discord.js to calling Discord API.  So as example mention when we using express + top.gg/sdk . on Vote event I want to pass discord.js created shard client so that I can send message to users but. As you talk before there is no way to pass it so I would like to know how can we handle this situation

**Comment by jpbberry** [comment]
Host the webhook on your master process, then use the raw Discord API to DM the user would be my suggestion. If you want to stay using discord.js for full interaction you can do an eval on like shard 0 or something via the sharding manager.

**Comment by velddev** [comment]
> as example mention when we using express + top.gg/sdk . on Vote event I want to pass discord.js created shard client so that I can send message to users but.

It's recommended to either DM the user, which always goes through Shard 0, Discord.JS should handle this automatically. Or, you can use `guild_id % shard_count` to get the proper shard for the guild. 

This isn't implemented by design to keep our sdk library-agnostic.

**Comment by HellCatVN** [comment]
I know that discord.js will handle how to send DM to user but In my case I just want to know that where I can initial webhook server . If it is shard 0 it will break the load balance structure cause shard 0 will handle too much request to send message while other shard is doing nothing.

**Comment by jpbberry** [comment]
I don't think this is a good way to look at it. Truly a webhook sending DMs is not that big of a load change. If it's really that important you should probably understand how to do it in a separate process anyways. The easiest way is to host it on shard 0. And it'll even have the same ratelimit handler making it unable to break Discord ratelimits than if you hosted it on each shard (somehow) or raw API.

**Comment by jpbberry** [comment]
At this point this is unrelated to the library. If you need help doing something or recommendation on how to use the webhook I suggest you use the development chat inside of the Discord server.
