### ISSUE TITLE
Not showing up in log.

### ISSUE THREAD

**Issue by JGriffin34432** [DiscordBotList/dblapi.js#6]
For some reason, the api is not showing up in the console.

``

[index.js for music-cord.txt](https://github.com/DiscordBotList/dblapi.js/files/1844687/index.js.for.music-cord.txt)

**Comment by tonkku107** [comment]
What are you expecting exactly?    
The module only logs errors into the console by itself

**Comment by JGriffin34432** [comment]
oh ok.
