### ISSUE TITLE
Autoposter is returning error when I tried to post stats

### ISSUE THREAD

**Issue by hemanth351718** [DiscordBotList/dblapi.js#66]
#### Expected Behavior
Expected autoposter will post my stats to top.gg

#### Observed Behavior
It is returning 403 to my console when I tried to post stats.

**Comment by jpbberry** [comment]
403's and 401's are encountered when you're not providing a token or your token is invalid. Have you added the token? Is your bot approved?

**Comment by hemanth351718** [comment]
Yes, my bot is approved and I have added the correct webhook token. It returned error for first 2 days and now is fixed. Thanks <3
