### ISSUE TITLE
Requests are not being sent to the correct path

### ISSUE THREAD

**Issue by Nickanda** [DiscordBotList/dblapi.js#68]
Hi all,

I have tried to use the topgg-autoposter library to automatically send my stats to Top.gg, but it seems that every time the autoposter posts the stats, I get an error stemming from the SDK. I am not sure if my stats are correctly updating as a result of this.

```
0|IceCream | TopGGAPIError: 502 Bad Gateway
0|IceCream |     at Api._request (/home/NIck/IceCreamShop/node_modules/@top-gg/sdk/dist/structs/Api.js:76:19)
0|IceCream |     at runMicrotasks (<anonymous>)
0|IceCream |     at processTicksAndRejections (node:internal/process/task_queues:93:5)
0|IceCream |     at async Api.postStats (/home/NIck/IceCreamShop/node_modules/@top-gg/sdk/dist/structs/Api.js:99:9) {
0|IceCream |   response: Response {
0|IceCream |     size: 0,
0|IceCream |     timeout: 0,
0|IceCream |     [Symbol(Body internals)]: { body: [PassThrough], disturbed: true, error: null },
0|IceCream |     [Symbol(Response internals)]: {
0|IceCream |       url: 'https://top.gg/api//bots/stats',
0|IceCream |       status: 502,
0|IceCream |       statusText: 'Bad Gateway',
0|IceCream |       headers: [Headers],
0|IceCream |       counter: 0
0|IceCream |     }
0|IceCream |   }
0|IceCream | }
```

I am currently running @top-gg/sdk version 3.1.2 and topgg-autoposter version 2.0.0. Any help will be greatly appreciated.

Thanks.

**Comment by ghost** [comment]
top.gg was down moments ago

**Comment by VoltrexKeyva** [comment]
Most of the 5xx errors including this one isn't caused by the SDK itself, it is an issue with the top.gg API with the website either being down completely or something similar, it should be fixed after a while, if not and the error persists, I suggest either resesting your top.gg token or waiting longer I guess.

**Comment by Nickanda** [comment]
Seems like the issue resolved itself, didn't realize that top.gg was down. Thanks for the help! :)
