### ISSUE TITLE
Mark @types/express as a non dev dependancy

### ISSUE THREAD

**Issue by hsnbozkurt** [DiscordBotList/dblapi.js#80]
when i want to use this package with typescript the compiler complains
tsc
node_modules/@top-gg/sdk/dist/structs/Webhook.d.ts:1:49 - error TS2307: Cannot find module 'express' or its corresponding type
declarations.

1 import { Request, Response, NextFunction } from "express";
                                                  ~~~~~~~~~


Found 1 error in node_modules/@top-gg/sdk/dist/structs/Webhook.d.ts:1

**Comment by dev-bun** [comment]
For this, you should install the following:
```js
npm install @types/express express --save-dev
```
This installs the typing and should stop that error.

[See here for reference](https://stackoverflow.com/a/54586723)
