### ISSUE TITLE
Undocumented constructor overloads

### ISSUE THREAD

**Issue by ZLima12** [DiscordBotList/dblapi.js#9]
It seems like the constructor for the DBLAPI class has an undocumented overload: the client object can be passed in the options place.

https://github.com/DiscordBotList/dblapi.js/blob/5f70adaf2d0c6842341eda8bd5d9d14ff7ac929e/src/index.js#L28-L31

Is this still desired? If so, I'll update the typings. It would be wise to update the documentation as well.

**Comment by tonkku107** [comment]
The documentation does contain it

**Comment by ZLima12** [comment]
Oh, I see now. It wasn't as clear as I had thought it might be. In that case I'll update the typings.

**Comment by ZLima12** [comment]
![2018-04-25-082101_1916x1041_scrot](https://user-images.githubusercontent.com/17912528/39245888-f6d413b4-4862-11e8-834b-91366feab4c8.png)
Maybe something like this would be possible? Just to be as clear as possible.

**Comment by tonkku107** [comment]
Added that in the latest docs
